### ISSUE TITLE
Alt Character Sheet Usage - Suggestion

### ISSUE THREAD

**Issue by MrBrentRogers** [Mary-Usagi/spellpoints5e#2]
Are you working on allowing this Mod to work with Alt Character Sheets?

I don't use "Tidy5e" but I do use "Compact D&D Beyond-like" 
https://github.com/ElfFriend-DnD/foundryvtt-compactBeyond5eSheet

Wondering if moving the Spell Points to the Top of the Spell List or as another Resource would work natively for more Alt Character Sheets.

 I think having the module add a second line at the top of Spellbook would make this work.

**Comment by Mary-Usagi** [comment]
Should work for your module now. I added an option in the settings to display the spell points where the resources are in the character sheet. 
But it's not a great fix, as for example tidy5e uses a completely different class naming scheme, which makes it hard to insert it the same way (and doesn't work yet). Other sheets probably also use other names etc. 

I'm pretty new to foundry development, so there's probably a way better solution, but I don't know that yet. >.<

**Comment by Mary-Usagi** [comment]
Top of the spell list would probably be the best way if I think about it. I'll try that next.. ^^ But will probably take some time.
