### ISSUE TITLE
Usable Resource

### ISSUE THREAD

**Issue by MrBrentRogers** [Mary-Usagi/spellpoints5e#3]
Is there a way to have abilities or resources use the Spell Points?

**Comment by Mary-Usagi** [comment]
Hm, not really sure what you mean. Could you give an example?

**Comment by MrVauxs** [comment]
Is it possible to have Spell Points as a selectable resource when using an ability. For example, there are Sorcerer homebrews that convert their spell slots into spell points, which is not just used for casting spells but also for metamagic. Thus, you'd want to have metamagic features be able to consume spell points.

**Comment by Mary-Usagi** [comment]
Update: I found it!

If you install the module `Dynamic effects using Active Effects` you can select the spell points via `flags.spellpoints5e.resources.points.value` as a resource, set a value and use it with weapons, features, whatever you want. :D 

I don't think I'll support that natively in my module (not yet at least), as it seems a little complicated. But I'll keep it in mind.
